---
- include: stable.yml
  when: kube_build == "stable"

- include: testing.yml
  when: kube_build == "testing"

- name: Get the node token values
  become: yes
  slurp:
    src: "{{ kube_token_dir }}/{{ item }}-{{ inventory_hostname }}.token"
  with_items:
    - "system:kubelet"
    - "system:proxy"
  register: tokens
  run_once: true
  delegate_to: "{{ groups[master_group_name][0] }}"
  tags:
    - minion

- name: Set token facts
  set_fact:
    kubelet_token: "{{ tokens.results[0].content|b64decode }}"
    proxy_token: "{{ tokens.results[1].content|b64decode }}"
  tags:
    - minion

- name: write the config files for kubelet
  become: yes
  template: src=kubelet.j2 dest={{ kube_config_dir }}/kubelet
  notify:
    - restart kubelet
  tags:
    - minion

- name: write the kubecfg (auth) file for kubelet
  become: yes
  template: src=kubelet.kubeconfig.j2 dest={{ kube_config_dir }}/kubelet.kubeconfig
  notify:
    - restart kubelet
  tags:
    - minion

- name: write the config files for proxy
  become: yes
  template: src=proxy.j2 dest={{ kube_config_dir }}/proxy
  notify:
    - restart proxy
  tags:
    - minion

- name: write the kubecfg (auth) file for kube-proxy
  become: yes
  template: src=proxy.kubeconfig.j2 dest={{ kube_config_dir }}/proxy.kubeconfig
  notify:
    - restart proxy
  tags:
    - minion

- name: Enable kubelet
  become: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - minion

- name: Enable proxy
  become: yes
  service:
    name: kube-proxy
    enabled: yes
    state: started
  tags:
    - minion

- name: addons | Logging | Create Fluentd pod
  become: yes
  copy:
    src: fluentd-es.yaml
    dest: "{{ kube_manifest_dir }}/fluentd-es.yaml"
  when: enable_logging
  tags:
    - addons
    - logging
