language: python
env:
  matrix:
     - TERRAFORM_FILE=testing/aws.tf ANSIBLE_PLAYBOOK=terraform.sample.yml
     - TERRAFORM_FILE=testing/do.tf  ANSIBLE_PLAYBOOK=terraform.sample.yml
     - TERRAFORM_FILE=testing/gce.tf ANSIBLE_PLAYBOOK=terraform.sample.yml
    # - TERRAFORM_FILE=testing/aws.tf ANSIBLE_PLAYBOOK=kubernetes.yml
    # - TERRAFORM_FILE=testing/do.tf  ANSIBLE_PLAYBOOK=kubernetes.yml
    # - TERRAFORM_FILE=testing/gce.tf ANSIBLE_PLAYBOOK=kubernetes.yml

install: "pip install -r requirements.txt"
before_script:
  - ssh-keygen -N '' -f ~/.ssh/id_rsa && eval $(ssh-agent) && ssh-add ~/.ssh/id_rsa
  - ln -sf $ANSIBLE_PLAYBOOK terraform.yml
  - ln -sf $TERRAFORM_FILE terraform.tf
  - mkdir $HOME/bin && export PATH=$PATH:$HOME/bin
  - export TERRAFORM_VERSION=0.6.8
  - export TF_VAR_build_number=${TRAVIS_JOB_NUMBER/./-} # GCE doesn't like . in resource.name, so sub . for -
  - curl -SL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip -d $HOME/bin terraform.zip
script: testing/integration-test.sh
after_success: echo slack notification here

addons:
  apt:
    packages:
      - unzip
