---
- name: reconfig docker
  become: yes
  command: /bin/true
  notify:
    - stop docker
    - delete docker0
    - start docker

- name: restart flannel
  become: yes
  service:
    name: flanneld
    state: restarted

- name: stop docker
  become: yes
  service:
    name: docker
    state: stopped

- name: delete docker0
  become: yes
  command: ip link delete docker0
  ignore_errors: yes

- name: start docker
  become: yes
  service:
    name: docker
    state: started
