---
- name: restart consul
  become: yes
  command: /usr/local/bin/consul-rolling-restart.sh {{ consul_acl_master_token }}
  notify:
    - wait for consul to listen

- name: restart nginx-consul
  become: yes
  command: systemctl restart nginx-consul
