---
- name: install etcd
  become: yes
  yum:
    name: etcd-{{ etcd_version }}
    state: present
  tags:
    - etcd

- name: generate systemd environment file
  become: yes
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart etcd
  tags:
    - etcd

- name: install etcd launch script
  become: yes
  copy:
    src: etcd-service-start.sh
    dest: /usr/local/bin
    mode: 0755
  notify:
    - restart etcd
  tags:
    - etcd

- name: create etcd.service.d
  become: yes
  file:
    dest: /etc/systemd/system/etcd.service.d
    state: directory
  tags:
    - etcd

- name: create local etcd service override
  become: yes
  copy:
    dest: /etc/systemd/system/etcd.service.d/local.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/local/bin/etcd-service-start.sh
  notify:
    - restart etcd
  tags:
    - etcd

- name: install consul check script
  become: yes
  template:
    src: consul-check-etcd-member
    dest: /usr/local/bin
    mode: 0755
  when: consul_dc_group is defined
  tags:
    - etcd

- name: register etcd with consul
  become: yes
  copy:
    src: etcd-service.json
    dest: /etc/consul
  when: consul_dc_group is defined
  notify:
    - reload consul
  tags:
    - etcd

- name: enable and start etcd
  become: yes
  service:
    name: etcd
    enabled: yes
    state: started
  tags:
    - etcd

- include: skydns.yml
  when: dns_setup is defined

- meta: flush_handlers
