---
- name: restart daemons
  become: yes
  command: /bin/true
  notify:
    - restart apiserver
    - restart controller-manager
    - restart scheduler
    - restart proxy

- name: restart apiserver
  become: yes
  service:
    name: kube-apiserver
    state: restarted
  when: inventory_hostname in groups[master_group_name][0]

- name: restart controller-manager
  become: yes
  service:
    name: kube-controller-manager
    state: restarted
  when: inventory_hostname in groups[master_group_name][0]

- name: restart scheduler
  become: yes
  service:
    name: kube-scheduler
    state: restarted
  when: inventory_hostname in groups[master_group_name][0]

- name: restart proxy
  become: yes
  service:
    name: kube-proxy
    state: restarted
  when: inventory_hostname in groups[master_group_name][0]
